PATH = 'data/'
PATH_OUTPUT = PATH+'output/'
PATH_INPUT  = PATH+'input/'
SRT_FOLDER = PATH_INPUT+'srt/'
TAG_FOLDER = PATH_OUTPUT+'tag/'

##*****--  INPUT --******##

FILE_WATCHED_IMDB = PATH_INPUT+'watched.imdb'
FILE_WATCHLIST_IMDB = PATH_INPUT+'watchlist.imdb'
FOLDER_SRT_TEST = SRT_FOLDER+'test'
FOLDER_SRT_TRAIN = SRT_FOLDER+'train'

##*****--  OUTPUT --******##

FILE_WATCHED_DATA = PATH_OUTPUT+'watched.data'
FILE_WATCHLIST_DATA = PATH_OUTPUT+'watchlist.data'
FOLDER_TAG_TEST = TAG_FOLDER+'test'
FOLDER_TAG_TRAIN = TAG_FOLDER+'train'